import type { SystemDesignTopic } from "../types.js";

export const systemDesignCurriculum: SystemDesignTopic[] = [
  { id: "latency-throughput-availability", stage: "fundamentals", title: "Latency, Throughput, and Availability", summary: "The core vocabulary for judging whether a system is usable at scale.", exampleSystems: ["YouTube", "Google Search"], prerequisites: [] },
  { id: "client-server-apis", stage: "fundamentals", title: "Client-Server Architecture and APIs", summary: "How requests move through clients, servers, protocols, and contracts.", exampleSystems: ["Instagram", "Amazon"], prerequisites: ["latency-throughput-availability"] },
  { id: "load-balancing", stage: "components", title: "Load Balancing", summary: "Distributing traffic across machines to improve availability and throughput.", exampleSystems: ["WhatsApp", "Netflix"], prerequisites: ["client-server-apis"] },
  { id: "caching", stage: "components", title: "Caching", summary: "Saving expensive results close to where they are needed.", exampleSystems: ["YouTube", "Amazon"], prerequisites: ["latency-throughput-availability"] },
  { id: "rate-limiting", stage: "components", title: "Rate Limiting", summary: "Protecting systems from overload, abuse, and noisy clients.", exampleSystems: ["Payment System", "API Gateway"], prerequisites: ["load-balancing"] },
  { id: "api-gateway", stage: "components", title: "API Gateway", summary: "A front door for routing, auth, limits, and cross-cutting API concerns.", exampleSystems: ["Uber", "Food Delivery"], prerequisites: ["rate-limiting"] },
  { id: "database-indexing", stage: "data-storage", title: "Database Indexing", summary: "Making reads fast by maintaining searchable data structures.", exampleSystems: ["Amazon", "Google Search"], prerequisites: ["client-server-apis"] },
  { id: "replication", stage: "data-storage", title: "Replication", summary: "Keeping copies of data for reads, locality, and resilience.", exampleSystems: ["Instagram", "Netflix"], prerequisites: ["database-indexing"] },
  { id: "sharding-partitioning", stage: "data-storage", title: "Sharding and Data Partitioning", summary: "Splitting data so storage and traffic can scale horizontally.", exampleSystems: ["WhatsApp", "URL Shortener"], prerequisites: ["replication"] },
  { id: "consistency-models", stage: "distributed-systems", title: "Consistency Models", summary: "Choosing what users are allowed to observe during concurrent updates.", exampleSystems: ["Payment System", "Google Docs"], prerequisites: ["replication"] },
  { id: "cap-theorem", stage: "distributed-systems", title: "CAP Theorem", summary: "Reasoning about consistency and availability during network partitions.", exampleSystems: ["DynamoDB-style stores", "Cassandra-style stores"], prerequisites: ["consistency-models"] },
  { id: "message-queues", stage: "distributed-systems", title: "Message Queues", summary: "Decoupling producers and consumers with durable asynchronous work.", exampleSystems: ["Notification System", "Food Delivery"], prerequisites: ["api-gateway"] },
  { id: "kafka-event-streaming", stage: "distributed-systems", title: "Kafka and Event Streaming", summary: "A durable event log for high-volume stream processing.", exampleSystems: ["Netflix", "Uber"], prerequisites: ["message-queues"] },
  { id: "idempotency", stage: "reliability-scaling", title: "Idempotency", summary: "Making retries safe when clients or networks fail.", exampleSystems: ["Payment System", "Order Checkout"], prerequisites: ["message-queues"] },
  { id: "distributed-locks", stage: "reliability-scaling", title: "Distributed Locks", summary: "Coordinating exclusive work across multiple machines.", exampleSystems: ["Inventory System", "Scheduled Jobs"], prerequisites: ["consistency-models"] },
  { id: "fault-tolerance", stage: "reliability-scaling", title: "Fault Tolerance", summary: "Designing systems that keep working when parts fail.", exampleSystems: ["WhatsApp", "Uber"], prerequisites: ["replication", "load-balancing"] },
  { id: "observability", stage: "reliability-scaling", title: "Observability", summary: "Using logs, metrics, traces, and alerts to understand production behavior.", exampleSystems: ["Netflix", "Payment System"], prerequisites: ["fault-tolerance"] },
  { id: "service-discovery", stage: "advanced-architecture", title: "Service Discovery", summary: "Finding healthy service instances in dynamic environments.", exampleSystems: ["Kubernetes", "Uber"], prerequisites: ["load-balancing"] },
  { id: "event-driven-architecture", stage: "advanced-architecture", title: "Event-Driven Architecture", summary: "Building systems around facts that happened rather than direct calls.", exampleSystems: ["Amazon", "Food Delivery"], prerequisites: ["kafka-event-streaming", "idempotency"] },
  { id: "distributed-transactions", stage: "advanced-architecture", title: "Distributed Transactions and Sagas", summary: "Coordinating multi-service changes without pretending the network is local.", exampleSystems: ["Payment System", "Travel Booking"], prerequisites: ["event-driven-architecture", "consistency-models"] },
  { id: "consistent-hashing", stage: "advanced-architecture", title: "Consistent Hashing", summary: "Distributing keys while minimizing movement when nodes change.", exampleSystems: ["CDN", "Distributed Cache"], prerequisites: ["sharding-partitioning"] },
  { id: "cdn", stage: "advanced-architecture", title: "Content Delivery Networks", summary: "Serving static and media content from locations close to users.", exampleSystems: ["YouTube", "Netflix"], prerequisites: ["caching"] },
  { id: "design-url-shortener", stage: "complete-system-designs", title: "Design a URL Shortener", summary: "A compact end-to-end design that combines IDs, storage, caching, and analytics.", exampleSystems: ["bit.ly", "TinyURL"], prerequisites: ["database-indexing", "caching"] },
  { id: "design-notification-system", stage: "complete-system-designs", title: "Design a Notification System", summary: "A production-style design for email, push, SMS, and in-app notifications.", exampleSystems: ["WhatsApp", "Amazon"], prerequisites: ["message-queues", "idempotency"] },
  { id: "design-ride-sharing", stage: "complete-system-designs", title: "Design a Ride Sharing System", summary: "Matching, geo-indexing, dispatch, pricing, and real-time location.", exampleSystems: ["Uber", "Lyft"], prerequisites: ["event-driven-architecture", "service-discovery"] }
];
